name: yari_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^1.0.2
  diamond_fab: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/fordark_logo.png
   - images/logo_for_white_3.png
   - images/logo_for_white.png
   - images/logo_y.png
   - images/logo_y_w.png
   - images/logo.png
   - images/connectdevelop.png
   - images/terminal.png
   - images/puzzle.png
   - images/cogs.png
   #maps
   - images/yarilabs-contact-us-uk.jpg
   - images/yarilabs-contact-us.png
   #tech_logos
   - images/tech/androidsdk.png
   - images/tech/angular2.jpg
   - images/tech/clojure.png
   - images/tech/elixir.png
   - images/tech/elm.png
   - images/tech/elm2.png
   - images/tech/erlang.jpg
   - images/tech/es6.png
   - images/tech/ionic.png
   - images/tech/phoenix.png
   - images/tech/ruby.png
   - images/tech/ruby_logo.png
   - images/tech/rubyonrails.png
   - images/tech/typescript.jpg
   #contact_logos
   - images/contact/github-b.png
   - images/contact/github-bs.png
   - images/contact/github-w.png
   - images/contact/googleplus_b.png
   - images/contact/googleplus_w.png
   - images/contact/linkedin_b.png
   - images/contact/linkedin_w.png
   - images/contact/twitter-b.png
   - images/contact/twitter-w.png

  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
